---


- name: CalicoHandlers | Verify
  command: /bin/true
  notify:
      # - CalicoHandlers | Run all handlers
      - CalicoHandlers | Get expected number of calico pods
      - CalicoHandlers | Wait for calico pods to be avalaible
      - CalicoHandlers | Fail if calico pods are not avalaible


- name: CalicoHandlers | Get expected number of calico pods
  command: kubectl get ds calico-node -o=jsonpath='{.status.desiredNumberScheduled}' --namespace=kube-system #--kubeconfig /root/.kube/config
  register: expectedPods
  until: expectedPods is succeeded and expectedPods.stdout|int > 0
  retries: 20
  delay: 6
  run_once: true
  changed_when: false

- name: CalicoHandlers | Wait for calico pods to be avalaible
  command: kubectl get ds calico-node -o=jsonpath='{.status.numberReady}' --namespace=kube-system #--kubeconfig /root/.kube/config
  register: avalaiblePods
  until: expectedPods.stdout|int == avalaiblePods.stdout|int
  retries: 20
  delay: 6
  failed_when: false
  changed_when: false
  run_once: true

- name: CalicoHandlers | Fail if calico pods are not avalaible
  fail:
     msg: "Timed out waiting for all calico pods to be avalaible."
  run_once: true
  when: expectedPods.stdout|int != avalaiblePods.stdout|int