---

  - name: CoreDnsHandlers | Verify
    command: /bin/true
    notify:
      - CoreDnsHandlers | Get expected number of coreDNS replica 
      - CoreDnsHandlers | Wait for coreDNS pods to be avalaible
  

  - name: CoreDnsHandlers | Get expected number of coreDNS replica 
    command: kubectl get deployment coredns  -o=jsonpath='{.status.availableReplicas}' -n kube-system 
    register: expectedReplicas
    until: expectedReplicas is succeeded and expectedReplicas.stdout|int > 0
    retries: 30
    delay: 10
    #failed_when: false

  - name: CoreDnsHandlers | Wait for coreDNS pods to be avalaible
    command: kubectl get deployment coredns -o=jsonpath='{.status.readyReplicas}' --namespace=kube-system #--kubeconfig /root/.kube/config
    register: readyPods
    until: expectedReplicas.stdout|int == readyPods.stdout|int
    retries: 20
    delay: 6
    #failed_when: false
    #changed_when: false
    run_once: true