galaxy_info:
  author: ROK
  description: Installs CFSSL PKI toolkit
  license: GPLv3
  min_ansible_version: 2.2
  platforms:
  - name: Centos 
    versions:
    - 7.4
  galaxy_tags:
    - tls
    - certificate
    - ca
    - security
