---

## vagrant configure:  hostname to point to 127.0.0.1  in /etc/hosts file by default
## this is not good because, hostmanager plugin assign hostname --> eth1 address 
## it's conflict ! so we have to fix this shit, 'Yez zur'. in favor of hostmanager !!!
- name: remove node hostname pointing to loopback address
  replace:
    path: /etc/hosts
    regexp: '^(127\.0\.0\.1\s*)\s*.*({{ vagrant.domain_tld }})(\s+.*)?$'
    replace: '\1localhost'


- name: Re-gather facts
  setup:
  when: ansible_hostname != ansible_nodename

- name: Add mappings to /etc/hosts
  blockinfile:
    path: /etc/hosts
    content: "{{ lookup('template', 'templates/hosts.j2') }}"
    marker: "###  Ansible-Managed-Hosts-{mark}"
    backup: yes
    state: present
  register: blockinfile


- name: Add empty line a end of file
  lineinfile:
    dest: /etc/hosts
    line: ' '
  when: blockinfile is changed == true