---

- name: Check if (the requested version of) vboxguestadditions is installed
  shell: modinfo vboxguest 2>/dev/null|awk '/^version/{print $2}'
  register: vbox_guest_version
  changed_when: vbox_guest_version.stdout != vagrant.vbox_guest_version
  ignore_errors: yes


- block:
  - name: Check if the ISO file is present on guest
    stat: 
      path: "{{ vbox.iso_path }}"
    register: file_path
    ignore_errors: yes

  - name: Download iso, if not present on guest
    get_url:
      url: "{{ vbox.mirror }}/{{ vbox.version }}/VBoxGuestAdditions_{{ vbox.version }}.iso"
      dest: "{{ vbox.iso_path }}"

  - name: Loopback mount iso
    mount:
      name: "{{ vbox.iso_mount_path }}"
      src: "{{ vbox.iso_path }}"
      opts: "ro,loop"
      fstype: iso9660
      state: mounted

  - name: Install necessary packages for compiling
    yum:
      name: "{{ item }}"
      state: present
    with_items:
    - bzip2
    - dkms
    - gcc
    - make
    - "linux-headers-{{ ansible_kernel }}"

  - name: Register currently installed virtualbox packages
    shell: rpm -qa  | grep  virtualbox
    register: installed_packages

  - name: Determine if (the requested version of) vboxguestadditions is installed
    shell: modinfo vboxguest 2>/dev/null|awk '/^version/{print $2}'
    register: retreived_guest_version
    changed_when: vbox_guest_version.stdout != vbox.version
    ignore_errors: yes

  - name: remove installed packages
    yum:
      name: "{{ item }}"
      state: absent
    with_items: "{{ installed_packages.stdout_lines }}"

  - name: Try uninstall
    shell: "/bin/bash {{ vbox.iso_mount_path }}/VBoxLinuxAdditions.run uninstall --force"
    ignore_errors: yes

  - name: Build and install VBoxGuestAdditions from file (without x11)
    shell: "/bin/bash {{ vbox.iso_mount_path }}/VBoxLinuxAdditions.run --nox11"
    ignore_errors: yes

  - name: Unmount iso
    mount:
      name: "{{ vbox.iso_mount_path }}"
      src: "{{ vbox.iso_path }}"
      opts: "ro,loop"
      fstype: iso9660
      state: absent


  - name: Remove build logfiles, artefacts and ISO files
    file:
      name: "{{ item }}"
      follow: yes
      state: absent
    with_items:
      - "{{ vbox.iso_path }}"
      - "/opt/VBoxGuestAdditions-{{ vbox.version }}/src"
      - /var/lib/dkms/vboxguest
      - "/usr/src/vboxguest-{{ vbox_version }}"
      - /var/log/vboxadd-install.log
      - /var/log/vboxadd-install-x11.log
      - /var/log/VBoxGuestAdditions.log

  - name: Remove iso fstab entry
    lineinfile: >
      dest=/etc/fstab
      regexp='^{{ iso_download_path }}'
      line='{{ iso_download_path }}	{{ iso_mount_path }}	iso9660	ro,loop	0	0'
      state=absent
  when: (vbox_guest_version.stdout != vbox.version)


