---

  # setup directories
- name: create {{ kubeconfig_dir }} directory
  file: 
    path: "{{ kubeconfig_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: 0744
    
- name: copy kubectl config to remote
  template: 
     src: kubeconfig.j2 
     dest: "{{ kubeconfig_dir }}/config"
     owner: "{{ ansible_user }}"
     group: "{{ ansible_user }}"
     mode: 0755
