galaxy_info:
  author: René Okouya
  description: Install & Configure docker-engine.
  company: "Wescale"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.1
  platforms:
    - name: EL
      versions:
        - 7
  galaxy_tags:
    - docker

dependencies: []