---
  - name: Calico | create /etc/calico directory
    file:
      path: "/etc/calico"
      state: directory


  - name: Calico | install jq
    yum:
      name: jq
      state: present

  - name: Calico | copy calico rbac to spec dir
    template:
      src: "{{ item.name }}.j2"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: 0660
    with_items:
      - { name: calico-rbac.yml, dest: '{{ calico_dir }}/calico-rbac.yml' }


  - name: Calico | create calico RBAC roles
    command: kubectl apply -f /etc/calico/calico-rbac.yml --kubeconfig "{{ kube_config.kubectl }}"

  - name: Calico | copy calico deployments manifests to specs dir
    template:
      src: "{{ item.name }}.j2"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: 0660
    with_items:
        #- { name: calico-kubeconfig,        dest: '{{ kube_config.calico }}' }
        - { name: calico.yml,               dest: '{{ calico_dir }}/calico.yml' }
    register: calico_node_manifests


  - name: Calico | start calico containers
    command: kubectl apply -f /etc/calico/calico.yml --kubeconfig "{{ kube_config.kubectl }}"
    notify: CalicoHandlers | Verify
