---

  - name: Create specs directory
    file:
      path: "/etc/kubernetes/specs"
      state: directory
  
  - name: copy kube-proxy kubeconfig
    template:
      src: kube-proxy.kubeconfig.j2
      dest: "{{ kube_config.kubeproxy }}"
      owner: root
      group: root
      mode: 0664
    notify: restart kube-proxy service

  - name: copy kube-proxy.service
    template:
      src: 'kube-proxy.service.j2'
      dest: '/etc/systemd/system/kube-proxy.service'
      owner: root
      group: root
      mode: 0664
    notify:
      - restart kube-proxy service

  - meta: flush_handlers

  - name: verify kube-proxy is running
    command: systemctl status kube-proxy
    register: running
    until: running is success
    retries: 3
    delay: 5
