---

- name: Traefik | create specs directory
  file:
    path: "/etc/kubernetes/specs"
    state: directory


- name: Traefik | copy traefik deployments manifests to specs dir
  template:
      src: "{{ item.name }}.j2"
      dest: "{{ item.dest }}"
      owner: root
      group: root
      mode: 0660
  with_items:
        - { name: traefik-rbac.yml,         dest: '{{ kube_spec_dir }}/traefik-rbac.yml' }
        - { name: traefik-ds.yml,           dest: '{{ kube_spec_dir }}/traefik-ds.yml' }
        - { name: traefik-ui.yml,           dest: '{{ kube_spec_dir }}/traefik-ui.yml' }
  register: traefik_manifests

- name: Traefik | Create traefik rBac
  k8s:
    state: present
    src: /etc/kubernetes/specs/traefik-rbac.yml
    kubeconfig: "{{ kube_config.kubectl }}"

- name: Traefik | Start traefik daemontSet
  k8s:
    state: present
    src: /etc/kubernetes/specs/traefik-ds.yml
    kubeconfig: "{{ kube_config.kubectl }}"
  notify: TraefikHandlers | Verify

- name: trigger handlers now
  meta: flush_handlers

- name: Traefik | Start traefik ingress resource admin-ui
  k8s:
    state: present
    src: /etc/kubernetes/specs/traefik-ui.yml
    kubeconfig: "{{ kube_config.kubectl }}"